from backend.database import SessionLocal, engine
from backend.models import Base, Game, Player, Component

import enum

class ZoneType(str, enum.Enum):
    ACTIVE_EFFECT_CARDS_P1 = "active_effect_cards_p1"
    ACTIVE_EFFECT_CARDS_P2 = "active_effect_cards_p2"
    ACTIVE_EFFECT_CARDS_P3 = "active_effect_cards_p3"
    ACTIVE_EFFECT_CARDS_P4 = "active_effect_cards_p4"
    ACTIVE_EFFECT_CARDS_P5 = "active_effect_cards_p5"
    HAND_P1 = "hand_p1"
    HAND_P2 = "hand_p2"
    HAND_P3 = "hand_p3"
    HAND_P4 = "hand_p4"
    HAND_P5 = "hand_p5"
    RESEARCH_DECK = "research_deck"
    RESEARCH_DISCARD = "research_discard"
    INFLUENCE_DECK = "influence_deck"
    INFLUENCE_DISCARD = "influence_discard"
    SABOTAGE_DECK = "sabotage_deck"
    SABOTAGE_DISCARD = "sabotage_discard"
    BOARD = "board"

class ComponentType(str, enum.Enum):
    CARD = "card"

class CardCategory(str, enum.Enum):
    RESEARCH = "research"
    INFLUENCE = "influence"
    SABOTAGE = "sabotage"

def seed_initial_game():
    db = SessionLocal()

    try:
        # 2. Clear existing data (for debugging)
        # Base.metadata.drop_all(bind=engine)
        # Base.metadata.create_all(bind=engine)

        # 3. Create a New Game Instance
        new_game = Game(game_phase="setup")
        db.add(new_game)
        db.commit()
        db.refresh(new_game)  # Get the ID generated by the DB

        # 4. Create Players (TODO: add handling for more than 2 players)
        player_1 = Player(user_name="Player One", player_order=0, game_id=new_game.id)
        player_2 = Player(user_name="Player Two", player_order=1, game_id=new_game.id)
        db.add_all([player_1, player_2])

        # 5. Create Components (Cards and Pieces)
        # We'll put these in the 'DECK' zone initially
        cards_to_create = [
            Component(
                name="good_ol_corporate_espionage",
                comp_type=ComponentType.CARD.value,
                sub_type=CardCategory.INFLUENCE.value,
                zone=ZoneType.INFLUENCE_DECK.value,
                game_id=new_game.id
            ),
            Component(
                name="unethical_data_source",
                comp_type=ComponentType.CARD.value,
                sub_type=CardCategory.RESEARCH.value,
                zone=ZoneType.RESEARCH_DECK.value,
                game_id=new_game.id
            ),
            Component(
                name="hack_smart_toasters",
                comp_type=ComponentType.CARD.value,
                sub_type=CardCategory.SABOTAGE.value,
                zone=ZoneType.SABOTAGE_DECK.value,
                game_id=new_game.id)
        ]

        # Add a physical piece on the board (pos_x, pos_y)
        # Assuming a board size where center is 0,0 or standard metric 0-1000
        central_token = Component(
            name="Main_Hub_Token",
            comp_type="token",
            zone="BOARD",
            pos_x=500.0,
            pos_y=500.0,
            game_id=new_game.id
        )

        db.add_all(cards_to_create)
        db.add(central_token)

        # 6. Final Commit
        db.commit()
        print(f"Successfully seeded Game ID: {new_game.id} with players and components.")

    except Exception as e:
        print(f"Error seeding database: {e}")
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    seed_initial_game()